#!/bin/sh

: ${syslog_tcp_listen:=no}

if [ -n "$syslog_tcp_dest" ]; then
  syslog_tcp_dest_host=${syslog_tcp_dest%:*}
  if [ "$syslog_tcp_dest_host" != "$syslog_tcp_dest" ]; then
    syslog_tcp_dest_port=${syslog_tcp_dest#*:}
  fi
fi

: ${syslog_tcp_dest_port:=601}

umask 0022

cat > /etc/syslog-ng/syslog-ng.conf <<EOF
@version: 3.7

options {
  chain_hostnames(0);
  flush_lines(0);
  use_dns(no);
  use_fqdn(no);
  owner(root);
  group(adm);
  perm(0640);
  stats_freq(0);
};

source s_all {$(
  echo
  echo '  internal();'
  echo '  unix-dgram("/dev/log");'
  if [ "$syslog_tcp_listen" = "yes" ]; then
    echo '  syslog();'
  fi)
};

destination d_all {$(
  echo
  if [ -n "$syslog_tcp_dest_host" ]; then
    echo -n "  syslog(\"$syslog_tcp_dest_host\" "
    echo -n 'transport("tcp") '
    echo "port(\"$syslog_tcp_dest_port\"));"
  else
    echo '  pipe("/proc/1/fd/1");'
  fi)
};

log {
  source(s_all);
  destination(d_all);
};
EOF
